apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: shorts
spec:
  template:
    spec:
      containers:
      - image: australia-southeast2-docker.pkg.dev/shorted-dev-aba5688f/shorted/shorts:v0.2.2-726-gee7001f7-dirty
        ports:
        - containerPort: 9091
        env:
        - name: APP_STORE_POSTGRES_ADDRESS
          value: aws-0-ap-southeast-2.pooler.supabase.com:6543
        - name: APP_STORE_POSTGRES_DATABASE
          value: postgres
        - name: APP_STORE_POSTGRES_USERNAME
          value: postgres.xivfykscsdagwsreyqgf
        - name: APP_STORE_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: APP_STORE_POSTGRES_PASSWORD